AdvancedOptions: true
DockerFilePath: Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/metabase
RegionId: ap-southeast-1
CustomParameters: ''
DockerBuildArgs:
- ArgumentValue: latest
  ArgumentName: VERSION
Owner: linziqiaolzq
Branch: master
Platform: github
